-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 13:26:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Sobrenome` VARCHAR(80) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `DataNascimento` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `Sigla` CHAR(8) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `SuperArea` CHAR(8) NULL,
  PRIMARY KEY (`Sigla`),
  UNIQUE INDEX `Sigla_UNIQUE` (`Sigla` ASC) VISIBLE,
  INDEX `fk_Area_Area1_idx` (`SuperArea` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Area1`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Sigla` CHAR(8) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Horas` INT NULL,
  `Custo` DECIMAL(12,2) NOT NULL,
  `Area` CHAR(8) NOT NULL,
  PRIMARY KEY (`Sigla`),
  UNIQUE INDEX `Sigla_UNIQUE` (`Sigla` ASC) VISIBLE,
  INDEX `fk_CURSO_Area_idx` (`Area` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_Area`
    FOREIGN KEY (`Area`)
    REFERENCES `mydb`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matricula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `Curso` CHAR(8) NOT NULL,
  `Aluno` CHAR(11) NOT NULL,
  `Data` DATE NOT NULL,
  `Pago` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Curso`, `Aluno`),
  INDEX `fk_Matricula_Aluno1_idx` (`Aluno` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modulo` (
  `Sigla` CHAR(8) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Curso` CHAR(8) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Modulo_Curso1_idx` (`Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Curso_Sigla` CHAR(8) NOT NULL,
  PRIMARY KEY (`CPF`, `Curso_Sigla`),
  INDEX `fk_Professor_Curso1_idx` (`Curso_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso_Sigla`)
    REFERENCES `mydb`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Topicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Topicos` (
  `Modulo` CHAR(8) NOT NULL,
  `Sigla` CHAR(8) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Horas` INT NOT NULL,
  PRIMARY KEY (`Sigla`, `Modulo`),
  INDEX `fk_Topicos_Modulo1_idx` (`Modulo` ASC) VISIBLE,
  CONSTRAINT `fk_Topicos_Modulo1`
    FOREIGN KEY (`Modulo`)
    REFERENCES `mydb`.`Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
